import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
  NEXT_PUBLIC_CURRENCY_SYMBOL: z.string().default("Rs. "),
  DATABASE_URL: z.string().min(1).default("file:./dev.db"),
  ADMIN_EMAIL: z.string().email().default("admin@petalcraftflorals.com"),
  ADMIN_INITIAL_PASSWORD: z.string().min(8).default("ChangeMeInProd123!"),
  JWT_SECRET: z.string().min(16).default("petalcraft_jwt_super_secret_dev_key_replace_in_production_32chars"),
  STORAGE_PROVIDER: z.enum(["local", "cloudinary", "s3"]).default("local"),
  CLOUDINARY_CLOUD_NAME: z.string().optional(),
  CLOUDINARY_API_KEY: z.string().optional(),
  CLOUDINARY_API_SECRET: z.string().optional(),
  PAYMENT_MOCK_MODE: z.string().transform((v) => v === "true" || v === "1").default("true"),
  ESEWA_MERCHANT_CODE: z.string().default("EPAYTEST"),
  ESEWA_SECRET_KEY: z.string().default("8gBm/:&EnhH.1/q"),
  KHALTI_PUBLIC_KEY: z.string().default("test_public_key_mock"),
  KHALTI_SECRET_KEY: z.string().default("test_secret_key_mock"),
  FONEPAY_MERCHANT_CODE: z.string().default("TEST_MERCHANT"),
});

export const env = envSchema.parse({
  NODE_ENV: process.env.NODE_ENV,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_CURRENCY_SYMBOL: process.env.NEXT_PUBLIC_CURRENCY_SYMBOL,
  DATABASE_URL: process.env.DATABASE_URL,
  ADMIN_EMAIL: process.env.ADMIN_EMAIL,
  ADMIN_INITIAL_PASSWORD: process.env.ADMIN_INITIAL_PASSWORD,
  JWT_SECRET: process.env.JWT_SECRET,
  STORAGE_PROVIDER: process.env.STORAGE_PROVIDER,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  PAYMENT_MOCK_MODE: process.env.PAYMENT_MOCK_MODE,
  ESEWA_MERCHANT_CODE: process.env.ESEWA_MERCHANT_CODE,
  ESEWA_SECRET_KEY: process.env.ESEWA_SECRET_KEY,
  KHALTI_PUBLIC_KEY: process.env.KHALTI_PUBLIC_KEY,
  KHALTI_SECRET_KEY: process.env.KHALTI_SECRET_KEY,
  FONEPAY_MERCHANT_CODE: process.env.FONEPAY_MERCHANT_CODE,
});
